name: Format Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  format_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Read the content of PULL_REQUEST_TEMPLATE.md
        run: |
          template_file=".github/PULL_REQUEST_TEMPLATE.md"
          pr_number=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          pr_description=$(cat "$template_file")
          jq --null-input --arg body "$pr_description" \
            '{body: $body}' > formatted_description.json
          jq -r . body formatted_description.json > description.txt
          gh pr edit "$pr_number" --body "$(cat description.txt)"
